### ISSUE TITLE
📚 [Documentation] - Add ways of working to Seshat project readthedocs

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat#101]
### Section of Documentation

All

### Description of Improvement

# Pre-requisites

- [x] https://github.com/Seshat-Global-History-Databank/seshat/issues/23 so we can show RAs progress so far when consulting them on their respective pages

## Docs pages
- [x] ~~Could look similar to https://alan-turing-institute.github.io/trusted-research/~~ Live at https://seshat-global-history-databank.github.io/seshat/index.html
- Pages for processes for each role
    - [x] Seshat Admin
        - [x] GitHub workflow
        - [x] #103 
        - [ ] https://github.com/Seshat-Global-History-Databank/seshat/issues/104
        - [x] Setup documentation
        - [ ] #105
        - [ ] #106
        - [ ] #107
        - [x] How to edit readthedocs
        - [ ] "Adding new datasets to the database" page
            - [ ] Pre-requisite:  #70 
        - [x] #117
    - [x] Research Assistant (could we work with Matilda on some of these in advance of the workshop?)
        - [x] #108
        - [ ] #110
        - [x] #111
        - [x] #112 
        - [ ] #32 
    - [x] #113
    - [x] Seshat Expert
        - [ ] How to download CSV extracts and open them in Excel
        - [ ] How to use the Seshat comment system as a Seshat Expert (currently disabled) - Possibly just the same page as #112 
        - [ ] Reconcile internal and external Seshat Expert [roles](https://seshat-global-history-databank.github.io/seshat/index.html#project-roles) - may need to coordinate with Majid on this
    - [x] Public User (maybe don't need but could include some "how to use Seshat guides")
        - [x] How to suggest edits via the Seshat login system (this page should be linked to from "Seshat Expert" too) - Possibly just the same page as #112
    - [x] #115
    - [x] #116
    - [ ] #114
    - [x] #127 

## TODO

- [x] Consult with Seshat project people on how they are doing things currently for first draft of pages
- [x] Create separate issues for specific docs pages above
- [x] Do a PR with blank versions of all these pages
- ~~Make it so that anyone in the project can update the readthedocs and can give others access (i.e. ensure all RAs have write access)~~ Issue opening and PR fork process has been added to the "How to update these docs" page
- [ ] #102 
- [ ] Request a full review of the docs from Pieter, Peter, Dan, Jim …. . Pieter is happy to lead on this editing process.

### Benefits of Improvement

All ways of working are documented

### Definition of Done

- [ ] The documentation improvement has been developed on a branch.
- [ ] The new branch has been tested in the Staging website.
- [ ] A pull request has been created for the new branch to be merged into the main branch.
