### ISSUE TITLE
📚 [Documentation] - How to use the Seshat website edit and "Private comment" system to make and discuss data edits

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat#112]
### Section of Documentation

Research Assistant, Seshat Databank Admin

### Description of Improvement

- Screenshots and instructions explaining how the login/comment system works
- Should also explain how RAs and Seshat Databank Admins work collaboratively here
- Explanation that the comment system is intended for discussion of data edits and link to GitHub issues for Seshat website feature requests (unless the preferred method is for Seshat Databank Admins to always open issues themselves)
- Might need to be 2 separate pages for admins and RAs

### Benefits of Improvement

New starters know the project ways of working for how to make data edits 

### Additional Context

The Seshat RAs and Admins currently use an in-built feature of the website for handling requests for data edits made by RAs and Seshat Experts and a private comment system for discussion. It should be documented how this works for new starters to learn how and when to make/handle different kinds of edits to the data.

### TODO

- [x] Ed to schedule some time with Majid and/or RAs to learn how this works before documenting
    - Can also use this meeting to mention when I'm teaching people to open issues during the Vienna workshop, this also applies to general improvements (considering that the comment system *may* be best placed for discussion of data edits?)
    - [notes](https://hackmd.io/@edchalstrey/HJvtoSAk1e)

### Definition of Done

- [x] The documentation improvement has been developed on a branch.
- [x] A pull request has been created for the new branch to be merged into the main branch.

**Comment by edwardchalstrey1** [comment]
# Questions and notes

- The edit system is very complicated, it would be better if Majid was able to update these docs to make it as clear as possible all the ways edits can be made.
- It might make sense for Majid to record a video for navigation of the website and features - perhaps I can do a separate video for the maps and API: https://github.com/edwardchalstrey1/seshat/issues/142
- Who handles the edits after they are submitted for review? Unlike the private comment system where you can assign someone, this isn't clear
