### ISSUE TITLE
Discussion on adding settlements datasets to Seshat

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat#172]
### Description of Improvement

- [x] **In January:** Ed to email Jenny and Jakob Z, Peter and Daniel and Majid (cc Pieter) to discuss the dataset and what's needed. Do they want to do this before Christmas or in the new year?
- [x] Fill out this issue with details
    - [Google doc with info](https://docs.google.com/document/d/13-XGg9GrgloCCMgp0aXqzQjSjjCQo8s9_hpYmydNEM8/edit?usp=sharing)
- [ ] Work on #70 in tandem

Pieter's original email:

> Over the next months we will spin up two new Seshat projects and for these projects new tables need to be created within the Databank. However, this is more involved than you would think as we will be adding two new units of analysis. > As you know so far most of our data has been linked to polities (and we have some agricultural data linked to geographical areas which will be added to the databank at some point). Now, we would like to create 1) a dataset which has individuals as the unit of analysis and 2) a dataset which has settlements at its core. The first dataset will be used to test theories pertaining to leadership styles and the second to look at Bronze Age warfare and settlement patterns. ?> Would you be able to take this on? Obviously there will be many links with existing data as well and this needs to be linked/integrated.
 
> The timeline is this:
> Over the next month we will do some work on the leadership study and produce a rudimentary codebook and do so by hopefully trying out the codebook on a few case studies. I expect a first draft of the codebook to come your way earliest in a month’s time.
> Over the next month we will put together a draft of a codebook with some very initial data. This should be with you by the end of October. Of the two projects this one is the more urgent one so if you have to choose please focus on this one.

### Dependencies

This is the first time adding a new dataset to Seshat in bulk other than Cliopatria, so we should work on #70 in tandem

### Technical Notes

Determine whether it's just a case of adding a new Django model and command script to populate it, or if there is work to be done on visualising it etc

### Definition of Done

- [ ] The feature has been developed on a feature branch.
- [ ] The feature branch has been tested in the Staging website.
- [ ] A pull request has been created for the feature branch to be merged into the dev branch.

**Comment by edwardchalstrey1** [comment]
I will be added to an RA meeting week of the 13th Jan

**Comment by edwardchalstrey1** [comment]
### 13th Jan

- Mesopotamian settlement datasets
- Jenny not ready yet because they need to meet with "Zhiwu"
- Revisit in 2 weeks

**Comment by edwardchalstrey1** [comment]
Unlikely I will have time to work on this now as per Pieter F email on 21st Jan

**Comment by edwardchalstrey1** [comment]
# Meeting 13th Feb 2025

[hackmd notes](https://hackmd.io/@edchalstrey/Sk6o7SiKJe)

In summary:
1. Convert the existing ["capitals" in seshat db](https://seshat-db.com/core/capitals/) to "cities" and add some new columns. 
    - Also create a way to import from a few datasets that Jenny will provide: Chandler's, Modelski's
    - May also want to add an `is_capital` field. Also consider that Capital's have their own `year_from` and `year_to` - are these the years the cities existed or the years that those cities were capitals of the linked polities? Or perhaps this isn't even needed because of the distinction between [Polity capital](https://seshat-db.com/general/polity_capital/update/433/) and [Capital](https://seshat-db.com/core/capitals/135/update/)
2. There are some complex datasets such as *Allen et al* which need their own separate tables from the Cities one, but are linked to it - these don't need to be updatable, but simply have a "last imported on date X from source dataset" warning label

**Comment by edwardchalstrey1** [comment]
# Jenny R suggestion

![Image](https://github.com/user-attachments/assets/d4d332d0-af6f-4dfe-b499-7739ebca8772)
![Image](https://github.com/user-attachments/assets/d5377432-a75b-4b75-89c7-dcf9ca802ec5)
![Image](https://github.com/user-attachments/assets/4ae5b25d-ea79-4aa0-85e1-4851ac76a17a)
![Image](https://github.com/user-attachments/assets/e26d160c-f7bb-4ac4-b89d-0390f91852b9)

# Peter T reply

![Image](https://github.com/user-attachments/assets/9ccbd6e5-3175-45cc-ad2c-d52db5263489)

# Majid reply

The Capital and Polity Capital tables serve distinct roles: the Capital table captures all cities that have served as capitals of any polity, including their names, coordinates, current country and alternative names (but no year ranges as this table captures the general concept of a capital city and not its associations with polities). The Polity Capital table links polities to the entries in the Capital table, specifying the year range of their association (If no year range is mentioned, like the example Ed mentioned, it implies that the city was the capital of that polity for the whole duration of the polity). 

 

Capitals: [https://seshat-db.com/core/capitals/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fseshat-db.com%2Fcore%2Fcapitals%2F&data=05%7C02%7Cechalstrey%40turing.ac.uk%7C9a7ef9107e5d4225c5d308dd4d236ba0%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638751536704129870%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=EIP1Qf4IQeQuMD%2Bo%2FacmIOUzzGuq0DPWCEBBHDEikbY%3D&reserved=0)

 

Polity Capitals: [https://seshat-db.com/general/polity_capitals_all/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fseshat-db.com%2Fgeneral%2Fpolity_capitals_all%2F&data=05%7C02%7Cechalstrey%40turing.ac.uk%7C9a7ef9107e5d4225c5d308dd4d236ba0%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638751536704153543%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=ZGD9GPV069OwFkWZvflH%2FAuBBvMKCKa%2FvwAzLYhD69M%3D&reserved=0)

 

A similar structure can be applied to a new City table, with corresponding Polity City relationships. The City table will share similar attributes (to the capitals), and the Polity City table will capture the polity-city associations over time. We could also introduce a column in the City table, let's call it is_capital, which would be marked as True for cities that were capitals of the corresponding polity for the specified year range. This would allow us to make the Capital and Polity Capital tables obsolete after transferring relevant data from these two existing tables into the new City and Polity City tables, though this step is not strictly necessary.

 

For variables like population, area, and binary features (walls, temples, elite residences, etc.) or any other variable that relates to a city, we need to create separate tables to make proper associations, including the respective year ranges.

 

Each city will have its own dedicated page on the website, displaying its coded variables and listing the associated polities over time. Likewise, polity pages will include relevant city information.

# Peter T suggestion

Cities table. This will be a new addition to Seshat on which Ed is currently working. Once Ed implements this data structure, we will import the Reba dataset into it.
 
I don’t think we need a column “is_capital”. As long as we have a list of unique city names (e.g., avoid confusion between Buda and Budapest), this data will be inferred automatically from the rest of Seshat.
 
I also don’t think that we need to enter the relation between a city and a polity manually. It should be done automatically using the city coordinates and Cliopatria.
 
Ed implements this data structure, we import the Reba data into it and discuss how it needs to be modified. Each city will have a dedicated page, similar to the polity pages, but with many fewer variables (the list of variables to be determined).

**Comment by edwardchalstrey1** [comment]
TODO:

- [x] Determine the relationship between the existing Capitals data and Cities data
    - Cities should include capitals 
    - Perhaps we should turn capitals into cities after all
    - Could we have Cities instead of capitals and Polity_non_capital_city (other cities) in addition to Polity_capital
    - Can we link to the full "City" page from one column of the city table
    - If we're being ambitious we could have a map with all the associated polity shapes for that capital shown
- Create a branch that implements the City pages idea according to Majid's suggestion above
    - [x] Make a new page that initially just shows a particular capital (to be changed to city)
    - [x] Include the fields from the Capitals table on the City page, formatted in the same way
    - [x] Turn the table into the first section of the City page, same style as Polity page and call it "General"
    - [x] Move the update and delete buttons so they are for that entire section
    - [x] Add draft variable buttons that look like how editable variables look on the polity pages to the other variable sections
        - City Scale Variables
        - City Structure Variables
    - [x] ~~Rename Capital into City. No changes needed to the table fields.~~ Since "Capital" is referred to in so many places in the code, it makes more sense to just update headers in all pages and forms, and the `core/capitals/` url to `core/cities/`
    - [x] Change the title on the City update page to explain that it's just the City Identity and Location and link to the full city page
    - [x] Also mention on the city create page that there will be a City page created where additional variables can be edited
    - [x] Also link to the full city page in the cities table
    - [x] Add new Polity_city table:
        - `core.City` (formerly `core.Capital`), `general.Polity_capital` (unchanged) & `general.Polity_city` (new)
    - [x] Add the new Polity_city table and edit page
 
### TODO (sequential)

- [x] Set up the model and edit pages for `City_duration` (similar to the 5 `general/polity_duration` templates)
- [x] Update the `CityDetailView` to include duration
- [x] Link via the Duration edit button on the City page ~~**OR** let's not bother with this and just use the start and end dates on the Cities table~~ (Capitals table dates are not used, let's be consistent)
    - Note: there are currently 4 sets of dates available (5 including Cliopatria), the year_from/year_to on "Capitals" (unused), those on "Polity_capital" (years that the city was capital of that polity(, those on "Polity_city" (should mean years city was within that polity) and those on "City_duration" if we made it (doesn't yet exist, but should be the full duration of the city, perhaps the end date defaulting to present) 
- Create command scripts to load the Reba (modelski and Chandler) data to the `core.Cities` (currently still called `Capital`) table including adding the years to the new `City_duration` table ~~OR the `Cities` years~~
  - [x] Chandler
  - [ ] modelskiAncient
  - [ ] modelskiModern
- [ ] Use the coordinates to determine the polity of the city based on which Cliopatria and populate the `Polity_city` table 
    - The years of `Polity_city` can be used to determine the duration that City was in that polity, and these would be populated using the Cliopatria years 
    - Note: this probably can't be a script, since we want it to automatically update whenever a new City is added
- [ ] Update the "Polities this city within" on `core/cities/` to show the contents of polities as determined by `Polity_city` and link to the respective Polity pages
- [ ] Rename the "Capitals" model to "Cities" if feasible and all references to it so nothing breaks
- [x] Add non-capital cities to polity pages next to capitals
- [ ] Bug: Fix capitals and cities displaying on the polity pages e.g. why doesn't Polity 810 show Budapest (check if any of Jakob's bug issues are this)
- [ ] Set up the models for the remaining below variables, add an edit page for each and link via the edit button on the City page
- [ ] Get the dataset(s) relating to those variables


### Vars

General:
- Identity and location (controlled by existing Capital table which we rename to City)
  - [x] Alt names
  - [x] Polities (capital of)
  - [x] Polities (city within)
  - [x] Current Country
  - [x] Coordinates
- Temporal bounds
  - [ ] Duration

City Complexity Variables
- City Scale
  - [ ] Population
  - [ ] Area (ha)
- City Structures 
  - [ ] Defensive walls (absent/present)
  - [ ] Religious building (absent/present)
  - [ ] Elite residence (absent/present)
  - [ ] Ziggurats (absent/present)

**Comment by edwardchalstrey1** [comment]
Closing this as I have opened a new issue #253
