### ISSUE TITLE
✨ [Feature request -Majid-to-do-list] - <easier comment object retrieval>

### ISSUE THREAD

**Issue by MajidBenam** [Seshat-Global-History-Databank/seshat#206]
### Description of Improvement

Not so urgent, but I need to find a better way to go from a private comment instance to the object that is using it. Probably adding two columns to the private_comment table to record the table and the app_name. And/Or adding sme method on the model definition. 

### Definition of Done

- [ ] The feature has been developed on a feature branch.
- [ ] The feature branch has been tested in the Staging website.
- [ ] A pull request has been created for the feature branch to be merged into the dev branch.
