### ISSUE TITLE
Schedule GitHub training

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat#41]
### Pre-requisite

- [x] Review issue templates and ensure they make sense
- [ ] Issue templates should exist on the API repo too

### TODO

- [ ] Training for opening issues , viewing the project board and general understanding of the GitHub organisation and repos. Also commenting on Pull Requests (where the incoming branch is checked out on a staging site link)
    - Pieter Francois (maybe him first before the others, so he can assess how difficult it is and provide names other than those in this list)
    - Peter Turchin
    - Jim Bennett (for now, this will be about him opening issues to Ed/Kalle/Majid, not issues being directed to him & the Cliopatria 
    - Anyone else likely to be making website development or API requests. This could end up being all of the Seshat RAs.
- [ ] Full developer training (see the [developer's guide](https://seshat-global-history-databank.github.io/seshat/contribute/developers-guide.html)) and how to update docs etc
    - Majid Benam

**Comment by edwardchalstrey1** [comment]
Probably worth thinking a bit further on the pipeline for feature requests - e.g. whether the 2 layer approach of the Seshat comment system, then GitHub issue is too convoluted or if it's actually appropriate. Perhaps some RAs with more specific requests should open issues directly whereas otherwise devs collate comments into issues - I'm not sure.

**Comment by edwardchalstrey1** [comment]
Related to https://github.com/edwardchalstrey1/seshat/issues/141

**Comment by edwardchalstrey1** [comment]
Closed in favour of https://github.com/Seshat-Global-History-Databank/seshat/issues/90
