### ISSUE TITLE
Discuss Cesium

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat#63]
PR https://github.com/Seshat-Global-History-Databank/seshat/pull/55 merges Cesium globe view into the dev branch, which can be seen on seshatdata.com (but not yet on live site seshat-db.com).

# Access token

- [x] Change the access token to allow free usage

# Cesium subscription

It looks like we might need to pay for [Cesium](https://ion.cesium.com/) to be allowed to use it in the context of a "funded research project" - however the pricing looks a bit steep:

<img width="571" alt="Screenshot 2024-08-12 at 13 27 41" src="https://github.com/user-attachments/assets/ad7a2626-a228-4f41-8ee5-83ba4ba54220">
<img width="359" alt="Screenshot 2024-08-12 at 13 45 46" src="https://github.com/user-attachments/assets/9a12d375-29f7-48b8-915b-cad4adb520e9">
<img width="421" alt="Screenshot 2024-08-12 at 13 46 27" src="https://github.com/user-attachments/assets/9c106daf-3bfd-4c8c-ba7a-19af61dd526c">

# TODO:

- [ ] Discuss with team whether it's worth including and whether we need to pay for it
- [ ] If answer is no, disable the feature
