### ISSUE TITLE
Set up new Seshat live site

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat#91]
### TODO

- [x] **Jim** to submit a version of Cliopatria we are happy to go live - **Update:** See https://github.com/Seshat-Global-History-Databank/cliopatria
- **Majid** to
    - [x] Set up new AWS VM and pull from new repo dev branch: https://github.com/Seshat-Global-History-Databank/seshat
        - seshatdata.com has been set up
    - [x] Set up a new production VM with the [setup](https://seshat-global-history-databank.github.io/seshat/admin/setup/cloud/CSH_manual.html) docs
    - [x] Ensure that the latest db dump is uploaded to the new production VM and [spatial datasets are loaded](https://seshat-global-history-databank.github.io/seshat/admin/setup/spatialdb.html)
    - [x] Test everything works as expected, e.g. users can login and make edits as expected
    - [x] Change seshat-db.com to point to to the new VM
    - [x] Shut down the old seshat-db.com VM

**Comment by edwardchalstrey1** [comment]
Hi @MajidBenam do you know when you plan to do this yet? Matilda was asking as she wants to be able to use the API with the most up to date Seshat data. If you set a date when you plan to do it, I can help with carrying out the Pull Request and code merge from your original repo with the recent changes on `Qing` branch.

**Comment by MajidBenam** [comment]
@edwardchalstrey1 Everything has been done on my personal website majidbenam.com and I am going to do it for seshat-db.com today. I have also revised my Notion documentation and will put everything into our GitHub Documentation. I have already checked the login system and API connections and connections to the database. Everything seem to be working fine now. But feel free to give it a try and see if there are things that do not work.

**Comment by MajidBenam** [comment]
@edwardchalstrey1  Quick question: Do we also need to import the data from GADM as in:
https://seshat-global-history-databank.github.io/seshat/admin/setup/spatialdb.html

**Comment by edwardchalstrey1** [comment]
> @edwardchalstrey1 Quick question: Do we also need to import the data from GADM as in: https://seshat-global-history-databank.github.io/seshat/admin/setup/spatialdb.html

Nice one Majid, yes this is needed for the "clickable borders" background map setting I created

**Comment by edwardchalstrey1** [comment]
I will merge #171 as well and do some testing on my end, so you can set the branch on seshat-db.com to be `dev`
